version: 2.1

orbs:
  node: circleci/node@4.9.0
  win: circleci/windows@2.2.0 

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: nvm install 8.10.0
      - run: nvm use 8.10.0
      - run: node -v
      - run: npm install --global --production windows-build-tools --vs2015
      - run: npm install node-gyp
      - run: npm install node-gyp -g
      - run: npm run build
      - store_artifacts:      
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - test/*      
  test:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .    
      - run: ls
      - run: pwd
      - run:
         command: test/test.sh
         shell: bash.exe   


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
