version: 2.1

orbs:
  node: circleci/node@4.9.0
  win: circleci/windows@2.2.0 

jobs:
  build:
    macos:
        xcode: 12
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Configure npm
          command: |
            npm config set registry https://npm-proxy.fury.io/kaleido/
      - node/install-packages:
          pkg-manager: npm
          cache-version: ${CACHE_VERSION}
      - run: npm run test
      - run: npm run build
      - store_artifacts:
          path: dist
  test:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: .    
      - run: ls
      - run: pwd
      - run: test/test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
